#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-macro-compat_2.12
Version  : 1.1.1
Release  : 3
URL      : https://github.com/milessabin/macro-compat/archive/v1.1.1.tar.gz
Source0  : https://github.com/milessabin/macro-compat/archive/v1.1.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar
Source2  : https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-macro-compat_2.12-data = %{version}-%{release}

%description
# macro-compat: cross version Scala macro support
**macro-compat** is a small library which, in conjunction with the [macro-paradise][macro-paradise] compiler plugin,
allows you to compile macros with Scala 2.10.x which are written to the Scala 2.11/2 macro API. This means that your
macros can be written just once, for the current API, and still be portable to earlier Scala releases.

%package data
Summary: data components for the mvn-macro-compat_2.12 package.
Group: Data

%description data
data components for the mvn-macro-compat_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar
/usr/share/java/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.pom
